// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgJqC-fjWgtMOTtBy-zrpo4ch6tQFBkS8',
    appId: '1:936369278381:web:3e2f31c5dc552a63da6524',
    messagingSenderId: '936369278381',
    projectId: 'medpredict-9794c',
    authDomain: 'medpredict-9794c.firebaseapp.com',
    storageBucket: 'medpredict-9794c.firebasestorage.app',
    measurementId: 'G-B1DRQGBPPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzCmFrS4Xx-ppryVo4G9LxPWnfb67pNxk',
    appId: '1:936369278381:android:92f66f148986610fda6524',
    messagingSenderId: '936369278381',
    projectId: 'medpredict-9794c',
    storageBucket: 'medpredict-9794c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaToM06NP7TwvhLceUpyIRKergjYB9Mvk',
    appId: '1:936369278381:ios:0dc12199a9aa426fda6524',
    messagingSenderId: '936369278381',
    projectId: 'medpredict-9794c',
    storageBucket: 'medpredict-9794c.firebasestorage.app',
    iosBundleId: 'com.example.medpredictAiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaToM06NP7TwvhLceUpyIRKergjYB9Mvk',
    appId: '1:936369278381:ios:0dc12199a9aa426fda6524',
    messagingSenderId: '936369278381',
    projectId: 'medpredict-9794c',
    storageBucket: 'medpredict-9794c.firebasestorage.app',
    iosBundleId: 'com.example.medpredictAiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgJqC-fjWgtMOTtBy-zrpo4ch6tQFBkS8',
    appId: '1:936369278381:web:75cf43153f7e1658da6524',
    messagingSenderId: '936369278381',
    projectId: 'medpredict-9794c',
    authDomain: 'medpredict-9794c.firebaseapp.com',
    storageBucket: 'medpredict-9794c.firebasestorage.app',
    measurementId: 'G-MHNMTQDR7W',
  );
}
